import { Inter } from 'next/font/google'
import './globals.css'
import Nav from './components/Nav'
import { CartProvider } from './context/CartContext'
import { AuthProvider } from './context/AuthContext'
import { PaymentProvider } from './context/PaymentContext'
import { ProductDataProvider } from './context/ProductDataContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <CartProvider>
          <PaymentProvider>
          <ProductDataProvider>
            <Nav />
            <main>
              {children}
            </main>
            </ProductDataProvider>
          </PaymentProvider>
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
